### PR TITLE
Fix concatenation of certificate chain

### PR DESCRIPTION
**Pull request by Slayer95**
Fixes Error: error:0906D066:PEM routines:PEM_read_bio:bad end line

### CODE REVIEW

**Comment by coolaj86** [comment]
If the server doesn't issue a chain then that is it's own problem and this PR would be a band-aid in the wrong place.

It seems like it was just an issue with the config files and you got it fixed though, right?

**Comment by Slayer95** [comment]
No. The issue is that the certificates should be separated with a new line.

**Comment by coolaj86** [comment]
They are separated with a newline:

https://github.com/Daplie/le-acme-core/blob/master/lib/get-certificate.js#L20

https://github.com/Daplie/le-acme-core/blob/master/lib/get-certificate.js#L330

https://github.com/Daplie/le-acme-core/blob/master/lib/get-certificate.js#L340,L342

**Comment by Slayer95** [comment]
Odd...

**Comment by coolaj86** [comment]
Can you give more details as to how you encountered the problem?

I haven't encountered this problem in my testing.

There may be something deeper that we can find.

**Comment by Slayer95** [comment]
This log resulted from trying to renew with [this script](https://gist.github.com/Slayer95/2098afb3de081e586cfc7ae72be527ef) certificates generated with letsencrypt-express@1.1.5.

https://gist.github.com/Slayer95/d4f04c175031579949d6477d40a93744

It's a run against the staging server, but the production server results in a similar one.
Furthermore, debugging with this [patch](https://github.com/Slayer95/le-sni-auto/commit/654af3536ee8d3bdb5fc05a7818248079f7ecbb3) reveals that the ``tls.createSecureContext()`` method is passed a [foul ``cert`` option](https://gist.github.com/Slayer95/1dc1e154107e8ec4cb7d4cc6200e7dc7).

**Comment by coolaj86** [comment]
Ah, okay, I need to deprecate v1.5. The bug fixes just introduced other bugs. The v1.x branch was just too much spaghetti code. Too difficult to test properly and get the desired results.

Use v2.x

**Comment by coolaj86** [comment]
v1.1.5 doesn't use le-sni-auto.... Or at least it shouldn't. That's a plugin for the v2.x branch only.

**Comment by Slayer95** [comment]
Sigh. I created the certs with 1.1.5. The renewal is with v2

**Comment by coolaj86** [comment]
@Slayer95 FYI We've moved to https://git.daplie.com/Daplie/le-sni-auto

**Pull request closed without merging**
